name: Docker Image CI

on:
  push:
    branches: [ "CD" ]
  pull_request:
    branches: [ "CD" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag thebottomonlne.azurecr.io/the-bottom-line-frontend:$(date +%s)
